# Generated by Django 5.1.7 on 2025-03-30 15:11

import django.utils.timezone
import files.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=files.models.user_directory_path)),
                ('filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('txt', 'Text'), ('word', 'Word'), ('other', 'Other')], default='other', max_length=10)),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('size', models.BigIntegerField(default=0)),
            ],
        ),
    ]
